#!/bin/bash
#
# Setup Databricks secrets for Neo4j MCP Server HTTP Connection (AWS AgentCore)
# Reads connection info from .mcp-credentials.json and creates secrets in Databricks
#
# Usage:
#   1. Deploy the Neo4j MCP server to AWS AgentCore using aws-starter:
#      https://github.com/neo4j-partners/aws-starter
#      Run: aws-starter neo4j-agentcore-mcp-server
#      Copy the generated .mcp-credentials.json to this directory
#   2. Run this script:
#      ./setup_databricks_secrets.sh [scope-name] [--profile PROFILE]
#      Examples:
#        ./setup_databricks_secrets.sh                              # Uses default scope and profile
#        ./setup_databricks_secrets.sh mcp-neo4j-secrets
#        ./setup_databricks_secrets.sh --profile my-workspace       # Custom Databricks CLI profile
#        ./setup_databricks_secrets.sh my-scope --profile staging
#   3. Use secrets in Databricks notebooks or HTTP connections
#
# Prerequisites:
#   - Databricks CLI installed and authenticated (databricks auth login --profile PROFILE)
#   - jq installed for JSON parsing
#   - .mcp-credentials.json in this directory (generated by aws-starter neo4j-agentcore-mcp-server)

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Parse arguments: [scope-name] [--profile PROFILE]
SCOPE_NAME="mcp-neo4j-secrets"
DATABRICKS_PROFILE=""
PROFILE_FLAG=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --profile)
            if [[ -z "${2:-}" ]]; then
                echo "Error: --profile requires a value"
                exit 1
            fi
            DATABRICKS_PROFILE="$2"
            PROFILE_FLAG="--profile $2"
            shift 2
            ;;
        -*)
            echo "Unknown option: $1"
            exit 1
            ;;
        *)
            SCOPE_NAME="$1"
            shift
            ;;
    esac
done

# Configuration
CREDENTIALS_FILE="$SCRIPT_DIR/.mcp-credentials.json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

echo ""
echo "============================================================"
echo "  Databricks Secrets Setup for Neo4j MCP (AWS AgentCore)"
echo "============================================================"
echo ""

log_info "Using secret scope: $SCOPE_NAME"
if [[ -n "$DATABRICKS_PROFILE" ]]; then
    log_info "Using Databricks profile: $DATABRICKS_PROFILE"
fi

# Check for .mcp-credentials.json
if [[ ! -f "$CREDENTIALS_FILE" ]]; then
    log_error ".mcp-credentials.json not found at: $CREDENTIALS_FILE"
    echo ""
    echo "This file is generated when you deploy the Neo4j MCP server using aws-starter."
    echo ""
    echo "1. Install and run aws-starter to deploy the Neo4j AgentCore MCP server:"
    echo "   https://github.com/neo4j-partners/aws-starter"
    echo ""
    echo "   aws-starter neo4j-agentcore-mcp-server"
    echo ""
    echo "2. Copy the generated .mcp-credentials.json to this directory:"
    echo "   cp /path/to/.mcp-credentials.json $SCRIPT_DIR/"
    echo ""
    exit 1
fi

# Check for jq
if ! command -v jq &> /dev/null; then
    log_error "jq is not installed"
    echo "Install with:"
    echo "  macOS:  brew install jq"
    echo "  Ubuntu: sudo apt-get install jq"
    echo "  Windows: choco install jq"
    exit 1
fi

# Check for Databricks CLI
if ! command -v databricks &> /dev/null; then
    log_error "Databricks CLI not found"
    echo ""
    echo "Install with: pip install databricks-cli"
    echo "Or: brew install databricks"
    echo ""
    echo "Then authenticate with: databricks auth login"
    exit 1
fi

# Verify Databricks authentication
log_step "Verifying Databricks CLI authentication..."
if ! databricks auth describe $PROFILE_FLAG &> /dev/null; then
    log_error "Databricks CLI is not authenticated"
    echo ""
    echo "Run: databricks auth login"
    echo "Or configure a profile in ~/.databrickscfg"
    exit 1
fi
log_info "Databricks CLI authenticated"

# Load values from .mcp-credentials.json
log_step "Loading configuration from .mcp-credentials.json"

GATEWAY_URL=$(jq -r '.gateway_url // empty' "$CREDENTIALS_FILE")
TOKEN_URL=$(jq -r '.token_url // empty' "$CREDENTIALS_FILE")
CLIENT_ID=$(jq -r '.client_id // empty' "$CREDENTIALS_FILE")
CLIENT_SECRET=$(jq -r '.client_secret // empty' "$CREDENTIALS_FILE")
OAUTH_SCOPE=$(jq -r '.scope // empty' "$CREDENTIALS_FILE")

# Extract gateway host from gateway_url (keep scheme, remove path)
# Example: https://xxx.bedrock-agentcore.us-west-2.amazonaws.com/mcp -> https://xxx.bedrock-agentcore.us-west-2.amazonaws.com
# Databricks HTTP connections require the https:// scheme in the host option
if [[ -n "$GATEWAY_URL" ]]; then
    GATEWAY_HOST=$(echo "$GATEWAY_URL" | sed -E 's|(https?://[^/]+).*|\1|')
else
    GATEWAY_HOST=""
fi

# Validate required values
missing=()
[[ -z "$GATEWAY_URL" ]] && missing+=("gateway_url")
[[ -z "$TOKEN_URL" ]] && missing+=("token_url")
[[ -z "$CLIENT_ID" ]] && missing+=("client_id")
[[ -z "$CLIENT_SECRET" ]] && missing+=("client_secret")
[[ -z "$OAUTH_SCOPE" ]] && missing+=("scope")

if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "Missing required values in .mcp-credentials.json: ${missing[*]}"
    echo ""
    echo "Ensure the credentials file contains all required OAuth2 values."
    echo "Re-run: aws-starter neo4j-agentcore-mcp-server"
    echo "See: https://github.com/neo4j-partners/aws-starter"
    exit 1
fi

log_info "Gateway URL: $GATEWAY_URL"
log_info "Gateway Host: $GATEWAY_HOST"
log_info "Token URL: $TOKEN_URL"
log_info "Client ID: $CLIENT_ID"
log_info "Client Secret: [REDACTED - ${#CLIENT_SECRET} characters]"
log_info "OAuth Scope: $OAUTH_SCOPE"

# Create secret scope (ignore error if already exists)
log_step "Creating secret scope: $SCOPE_NAME"
if databricks secrets create-scope "$SCOPE_NAME" $PROFILE_FLAG 2>/dev/null; then
    log_info "Secret scope created successfully"
else
    log_warn "Secret scope already exists (or failed to create - continuing)"
fi

# Function to set a secret
set_secret() {
    local key=$1
    local value=$2
    log_info "Setting secret: $key"
    # Use echo -n to avoid trailing newline, pipe to put-secret
    echo -n "$value" | databricks secrets put-secret "$SCOPE_NAME" "$key" $PROFILE_FLAG
}

# Set secrets for OAuth2 M2M authentication
log_step "Storing OAuth2 secrets in Databricks"

set_secret "gateway_host" "$GATEWAY_HOST"
set_secret "client_id" "$CLIENT_ID"
set_secret "client_secret" "$CLIENT_SECRET"
set_secret "token_endpoint" "$TOKEN_URL"
set_secret "oauth_scope" "$OAUTH_SCOPE"

log_info "All secrets stored successfully"

# Validate secrets were set
log_step "Validating secrets..."
echo ""
echo "Secrets in scope '$SCOPE_NAME':"
databricks secrets list-secrets "$SCOPE_NAME" $PROFILE_FLAG
echo ""

# Print usage instructions
log_info "Setup complete!"
echo ""
echo "============================================================"
echo "  Usage Instructions"
echo "============================================================"
echo ""
echo "1. In a Databricks notebook, retrieve secrets with dbutils:"
echo ""
echo "   SCOPE_NAME = \"$SCOPE_NAME\""
echo "   GATEWAY_HOST = dbutils.secrets.get(SCOPE_NAME, \"gateway_host\")"
echo "   CLIENT_ID = dbutils.secrets.get(SCOPE_NAME, \"client_id\")"
echo ""
echo "2. Create an HTTP connection with OAuth2 M2M (requires Unity Catalog):"
echo ""
echo "   CREATE CONNECTION neo4j_agentcore_mcp TYPE HTTP"
echo "   OPTIONS ("
echo "     host secret('$SCOPE_NAME', 'gateway_host'),"
echo "     base_path '/mcp',"
echo "     client_id secret('$SCOPE_NAME', 'client_id'),"
echo "     client_secret secret('$SCOPE_NAME', 'client_secret'),"
echo "     oauth_scope secret('$SCOPE_NAME', 'oauth_scope'),"
echo "     token_endpoint secret('$SCOPE_NAME', 'token_endpoint')"
echo "   );"
echo ""
echo "3. Use the HTTP connection to call MCP tools:"
echo ""
echo "   SELECT http_request("
echo "     conn => 'neo4j_agentcore_mcp',"
echo "     method => 'POST',"
echo "     path => '',"
echo "     headers => map('Content-Type', 'application/json'),"
echo "     json => '{\"jsonrpc\":\"2.0\",\"method\":\"tools/list\",\"id\":1}'"
echo "   );"
echo ""
echo "============================================================"
echo ""
echo "Note: Tool names are prefixed by the AgentCore Gateway:"
echo "  - neo4j-mcp-server-target___get-schema"
echo "  - neo4j-mcp-server-target___read-cypher"
echo ""
echo "Databricks handles OAuth2 token refresh automatically."
echo "This integration provides READ-ONLY access to Neo4j."
echo ""
